"use client";

import { useEffect, useState } from "react";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import {
  setCurrentBusinessFlow,
  setOptions,
  selectOption,
  Option,
} from "@/store/slices/outputSlice";
import FlowVisualization from "./FlowVisualization";
import OptionsDisplay from "./OptionsDisplay";
import { motion } from "framer-motion";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import {
  BarChart3,
  DownloadIcon,
  LineChart,
  PieChart,
  PlusSquare,
  Clipboard,
  AlertCircle,
} from "lucide-react";
import { Badge } from "../ui/badge";

const OutputInterface: React.FC = () => {
  const dispatch = useAppDispatch();
  const { options, selectedOptionId, currentBusinessFlow } = useAppSelector(
    (state) => state.output
  );
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("analysis");

  // Simulate loading data from API
  useEffect(() => {
    const timer = setTimeout(() => {
      // Mock current business flow
      const currentFlow = {
        nodes: [
          { id: "A", label: "Process A", position: { x: 50, y: 75 } },
          { id: "B", label: "Process B", position: { x: 200, y: 25 } },
          { id: "C", label: "Process C", position: { x: 350, y: 75 } },
        ],
        edges: [
          { id: "A-B", source: "A", target: "B" },
          { id: "B-C", source: "B", target: "C" },
        ],
      };

      // Mock optimization options
      const mockOptions: Option[] = [
        {
          id: "option-1",
          title: "Option A",
          description: "Optimize through process D",
          timeToImplement: "2 Months",
          costReduction: "-30% in cost",
          nodes: [
            { id: "A", label: "Process A", position: { x: 50, y: 75 } },
            { id: "D", label: "Process D", position: { x: 200, y: 25 } },
            { id: "C", label: "Process C", position: { x: 350, y: 75 } },
          ],
          edges: [
            { id: "A-D", source: "A", target: "D" },
            { id: "D-C", source: "D", target: "C" },
          ],
        },
        {
          id: "option-2",
          title: "Option B",
          description: "Optimize through processes E and F",
          timeToImplement: "3 Months",
          costReduction: "-25% in cost",
          nodes: [
            { id: "A", label: "Process A", position: { x: 50, y: 75 } },
            { id: "E", label: "Process E", position: { x: 175, y: 25 } },
            { id: "F", label: "Process F", position: { x: 250, y: 25 } },
            { id: "C", label: "Process C", position: { x: 350, y: 75 } },
          ],
          edges: [
            { id: "A-E", source: "A", target: "E" },
            { id: "E-F", source: "E", target: "F" },
            { id: "F-C", source: "F", target: "C" },
          ],
        },
      ];

      dispatch(setCurrentBusinessFlow(currentFlow));
      dispatch(setOptions(mockOptions));
      dispatch(selectOption(mockOptions[0].id));
      setLoading(false);
    }, 1000);

    return () => clearTimeout(timer);
  }, [dispatch]);

  const handleSelectOption = (optionId: string) => {
    dispatch(selectOption(optionId));
  };

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-gray-600">Generating optimization options...</p>
        </div>
      </div>
    );
  }

  const selectedOption = options.find((opt) => opt.id === selectedOptionId);

  return (
    <div className="h-full overflow-y-auto bg-gray-50 px-4 py-3">
      <div className="max-w-[1400px] mx-auto">
        {/* Dashboard Header */}
        <div className="flex justify-between items-center mb-4">
          <div>
            <h1 className="text-lg font-semibold text-gray-900">
              Business Operation Analysis
            </h1>
            <p className="text-sm text-gray-500">
              Updated April 27, 2025 · Generated by TARS Intelligence
            </p>
          </div>
        </div>

        {/* Dashboard Tabs */}
        <Tabs
          defaultValue="analysis"
          className="w-full mb-4"
          value={activeTab}
          onValueChange={setActiveTab}
        >
          <TabsList className="w-full justify-start bg-white border border-gray-200 rounded-md p-0.5 h-10">
            <TabsTrigger
              value="analysis"
              className="data-[state=active]:bg-blue-50 data-[state=active]:text-blue-700 rounded-sm h-8"
            >
              Analysis
            </TabsTrigger>
            <TabsTrigger
              value="recommendations"
              className="data-[state=active]:bg-blue-50 data-[state=active]:text-blue-700 rounded-sm h-8"
            >
              Recommendations
            </TabsTrigger>
            <TabsTrigger
              value="financials"
              className="data-[state=active]:bg-blue-50 data-[state=active]:text-blue-700 rounded-sm h-8"
            >
              Financial Impact
            </TabsTrigger>
            <TabsTrigger
              value="implementation"
              className="data-[state=active]:bg-blue-50 data-[state=active]:text-blue-700 rounded-sm h-8"
            >
              Implementation Plan
            </TabsTrigger>
          </TabsList>

          {/* Analysis Tab Content */}
          <TabsContent value="analysis" className="mt-4 space-y-4">
            {/* Key Stats */}
            <div className="metrics-grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
              <Card className="dashboard-card">
                <CardContent className="pt-4 pb-3">
                  <p className="stat-label">Current Annual Cost</p>
                  <p className="stat-value text-2xl font-semibold text-gray-900">
                    $340M
                  </p>
                  <div className="flex items-center mt-1">
                    <Badge
                      variant="outline"
                      className="text-xs bg-red-50 text-red-700 mr-2"
                    >
                      +12%
                    </Badge>
                    <span className="text-xs text-gray-500">
                      vs. Previous Year
                    </span>
                  </div>
                </CardContent>
              </Card>

              <Card className="dashboard-card">
                <CardContent className="pt-4 pb-3">
                  <p className="stat-label">Efficiency Rating</p>
                  <p className="stat-value text-2xl font-semibold text-gray-900">
                    68%
                  </p>
                  <div className="flex items-center mt-1">
                    <Badge
                      variant="outline"
                      className="text-xs bg-amber-50 text-amber-700 mr-2"
                    >
                      -3%
                    </Badge>
                    <span className="text-xs text-gray-500">
                      vs. Target (71%)
                    </span>
                  </div>
                </CardContent>
              </Card>

              <Card className="dashboard-card">
                <CardContent className="pt-4 pb-3">
                  <p className="stat-label">Process Time</p>
                  <p className="stat-value text-2xl font-semibold text-gray-900">
                    42 Days
                  </p>
                  <div className="flex items-center mt-1">
                    <Badge
                      variant="outline"
                      className="text-xs bg-red-50 text-red-700 mr-2"
                    >
                      +8 Days
                    </Badge>
                    <span className="text-xs text-gray-500">
                      Due to Tariff Delays
                    </span>
                  </div>
                </CardContent>
              </Card>

              <Card className="dashboard-card">
                <CardContent className="pt-4 pb-3">
                  <p className="stat-label">Risk Assessment</p>
                  <p className="stat-value text-2xl font-semibold text-gray-900">
                    High
                  </p>
                  <div className="flex items-center mt-1">
                    <AlertCircle className="h-3.5 w-3.5 text-red-600 mr-1" />
                    <span className="text-xs text-red-600">
                      Requires Immediate Action
                    </span>
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Current Business Flow */}
              <Card className="dashboard-card">
                <CardHeader className="pb-3 pt-4 border-b border-gray-100">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-base font-medium">
                      Current Business Operations Flow
                    </CardTitle>
                    <Badge variant="outline" className="bg-red-50 text-red-700">
                      At Risk
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="py-4">
                  <div className="mb-3">
                    <div className="flex items-center gap-2">
                      <div className="bg-red-100 text-red-800 rounded-md px-2 py-1 text-xs font-medium">
                        Critical Issue
                      </div>
                      <span className="text-sm">
                        Tariff Disruption at Process B
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 mt-2">
                      Current operations face significant delays due to new
                      tariff regulations. This has led to a projected $100M
                      increase in operational costs.
                    </p>
                  </div>
                  <div className="h-64 border border-gray-100 bg-white rounded-lg overflow-hidden">
                    <FlowVisualization
                      nodes={currentBusinessFlow.nodes}
                      edges={currentBusinessFlow.edges}
                    />
                  </div>
                </CardContent>
              </Card>

              {/* Options Display */}
              <Card className="dashboard-card">
                <CardHeader className="pb-3 pt-4 border-b border-gray-100">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-base font-medium">
                      Alternative Options
                    </CardTitle>
                    <Button variant="outline" size="sm" className="h-7 text-xs">
                      <PlusSquare className="h-3.5 w-3.5 mr-1" />
                      Custom Option
                    </Button>
                  </div>
                </CardHeader>
                <CardContent className="py-4">
                  <OptionsDisplay
                    options={options}
                    selectedOptionId={selectedOptionId}
                    onSelectOption={handleSelectOption}
                  />
                </CardContent>
              </Card>
            </div>

            {/* Context and Implementation */}
            <Card className="dashboard-card">
              <CardHeader className="pb-3 pt-4 border-b border-gray-100">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base font-medium">
                    Implementation Context
                  </CardTitle>
                  <Button variant="ghost" size="sm" className="h-7 text-xs">
                    <Clipboard className="h-3.5 w-3.5 mr-1" />
                    Copy Summary
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="py-4">
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  <div className="lg:col-span-2">
                    <h3 className="font-medium mb-2 text-sm">
                      Situation Overview
                    </h3>
                    <p className="text-sm text-gray-700 mb-4">
                      Current operations are facing significant disruptions due
                      to new tariff regulations affecting process B. These
                      regulations have led to increased costs and delays in the
                      supply chain, resulting in a projected $100M increase in
                      operational expenses.
                    </p>

                    <h3 className="font-medium mb-2 text-sm">
                      Recommended Approach
                    </h3>
                    <p className="text-sm text-gray-700">
                      The proposed changes aim to navigate these challenges
                      while minimizing operational costs by restructuring the
                      business flow. The selected option would require
                      structural changes in several departments but promises to
                      reduce costs by up to 30%.
                    </p>
                  </div>

                  <div className="lg:col-span-1">
                    <div className="border border-gray-200 rounded-lg p-4 bg-blue-50">
                      <h3 className="font-medium text-blue-800 mb-2 text-sm">
                        Implementation Timeline
                      </h3>

                      <div className="space-y-3">
                        <div className="flex items-start">
                          <div className="w-2 h-2 rounded-full bg-blue-600 mt-1.5 mr-2"></div>
                          <div>
                            <p className="text-xs font-medium">
                              Planning Phase
                            </p>
                            <p className="text-xs text-gray-600">2-3 weeks</p>
                          </div>
                        </div>

                        <div className="flex items-start">
                          <div className="w-2 h-2 rounded-full bg-blue-600 mt-1.5 mr-2"></div>
                          <div>
                            <p className="text-xs font-medium">
                              Process Redesign
                            </p>
                            <p className="text-xs text-gray-600">4-6 weeks</p>
                          </div>
                        </div>

                        <div className="flex items-start">
                          <div className="w-2 h-2 rounded-full bg-blue-600 mt-1.5 mr-2"></div>
                          <div>
                            <p className="text-xs font-medium">
                              Implementation
                            </p>
                            <p className="text-xs text-gray-600">6-8 weeks</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
              <CardFooter className="pt-0 border-t border-gray-100 py-3 flex justify-between">
                <div className="flex items-center">
                  <span className="text-sm text-gray-500">
                    Approval required from Operations Director
                  </span>
                </div>
                <Button>Approve Selected Option</Button>
              </CardFooter>
            </Card>
          </TabsContent>

          {/* Other tabs would be implemented similarly */}
          <TabsContent value="recommendations" className="mt-4">
            <Card className="dashboard-card">
              <CardHeader>
                <CardTitle>Detailed Recommendations</CardTitle>
              </CardHeader>
              <CardContent className="py-4">
                <p className="text-gray-600">
                  This section will contain detailed recommendations based on
                  the analysis.
                </p>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="financials" className="mt-4">
            <Card className="dashboard-card">
              <CardHeader>
                <CardTitle>Financial Impact Analysis</CardTitle>
              </CardHeader>
              <CardContent className="py-4">
                <p className="text-gray-600">
                  This section will contain financial projections and ROI
                  analysis.
                </p>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="implementation" className="mt-4">
            <Card className="dashboard-card">
              <CardHeader>
                <CardTitle>Implementation Plan</CardTitle>
              </CardHeader>
              <CardContent className="py-4">
                <p className="text-gray-600">
                  This section will contain a detailed implementation roadmap.
                </p>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default OutputInterface;
